let appointmentData = [
  {
    appointmentId: 1,
    userName: "User",
    salonName: "Elegant Hair Studio",
    serviceOrPackage: "Hair Style",
    status: "Active",
    bookingDate: "2024-11-12",
    paid: true,
    transactionId: 7,
    amount: 100
  },
  {
    appointmentId: 2,
    userName: "Partner",
    salonName: "Glamour Lounge",
    serviceOrPackage: "Hair Style",
    status: "Scheduled",
    bookingDate: "2024-11-13",
    paid: false,
    transactionId: 14,
    amount: 100
  },
  {
    appointmentId: 3,
    userName: "User",
    salonName: "Chic Cuts",
    serviceOrPackage: "Hair Style",
    status: "New",
    bookingDate: "2024-11-14",
    paid: true,
    transactionId: 22,
    amount: 100
  },
  {
    appointmentId: 4,
    userName: "Partner",
    salonName: "Luxe Locks",
    serviceOrPackage: "Hair Style",
    status: "Cancelled",
    bookingDate: "2024-11-15",
    paid: false,
    transactionId: 10,
    amount: 100
  },
  {
    appointmentId: 5,
    userName: "User",
    salonName: "Style Hub",
    serviceOrPackage: "Hair Style",
    status: "Scheduled",
    bookingDate: "2024-11-16",
    paid: true,
    transactionId: 19,
    amount: 100
  },
  {
    appointmentId: 6,
    userName: "Partner",
    salonName: "Elite Hair Lounge",
    serviceOrPackage: "Hair Style",
    status: "Active",
    bookingDate: "2024-11-17",
    paid: false,
    transactionId: 25,
    amount: 100
  },
  {
    appointmentId: 7,
    userName: "User",
    salonName: "Glam Shack",
    serviceOrPackage: "Hair Style",
    status: "New",
    bookingDate: "2024-11-18",
    paid: true,
    transactionId: 5,
    amount: 100
  },
  {
    appointmentId: 8,
    userName: "Partner",
    salonName: "Modern Makeovers",
    serviceOrPackage: "Hair Style",
    status: "Active",
    bookingDate: "2024-11-19",
    paid: false,
    transactionId: 3,
    amount: 100
  },
  {
    appointmentId: 9,
    userName: "User",
    salonName: "Vivid Hair Studio",
    serviceOrPackage: "Hair Style",
    status: "Cancelled",
    bookingDate: "2024-11-20",
    paid: true,
    transactionId: 17,
    amount: 100
  },
  {
    appointmentId: 10,
    userName: "Partner",
    salonName: "Radiant Salon",
    serviceOrPackage: "Hair Style",
    status: "Scheduled",
    bookingDate: "2024-11-21",
    paid: false,
    transactionId: 12,
    amount: 100
  },
  {
    appointmentId: 11,
    userName: "User",
    salonName: "Shine and Style",
    serviceOrPackage: "Hair Style",
    status: "New",
    bookingDate: "2024-11-22",
    paid: true,
    transactionId: 9,
    amount: 100
  },
  {
    appointmentId: 12,
    userName: "Partner",
    salonName: "Perfect Cuts",
    serviceOrPackage: "Hair Style",
    status: "Active",
    bookingDate: "2024-11-23",
    paid: true,
    transactionId: 2,
    amount: 100
  },
  {
    appointmentId: 13,
    userName: "User",
    salonName: "Classic Styles",
    serviceOrPackage: "Hair Style",
    status: "Cancelled",
    bookingDate: "2024-11-24",
    paid: false,
    transactionId: 16,
    amount: 100
  },
  {
    appointmentId: 14,
    userName: "Partner",
    salonName: "Urban Hair",
    serviceOrPackage: "Hair Style",
    status: "Scheduled",
    bookingDate: "2024-11-25",
    paid: true,
    transactionId: 11,
    amount: 100
  },
  {
    appointmentId: 15,
    userName: "User",
    salonName: "Royal Salon",
    serviceOrPackage: "Hair Style",
    status: "Active",
    bookingDate: "2024-11-26",
    paid: false,
    transactionId: 21,
    amount: 100
  },
  {
    appointmentId: 16,
    userName: "Partner",
    salonName: "Trendsetters",
    serviceOrPackage: "Hair Style",
    status: "New",
    bookingDate: "2024-11-27",
    paid: true,
    transactionId: 4,
    amount: 100
  },
  {
    appointmentId: 17,
    userName: "User",
    salonName: "Glamify",
    serviceOrPackage: "Hair Style",
    status: "Cancelled",
    bookingDate: "2024-11-28",
    paid: false,
    transactionId: 29,
    amount: 100
  },
  {
    appointmentId: 18,
    userName: "Partner",
    salonName: "Beauty Haven",
    serviceOrPackage: "Hair Style",
    status: "Scheduled",
    bookingDate: "2024-11-29",
    paid: true,
    transactionId: 6,
    amount: 100
  },
  {
    appointmentId: 19,
    userName: "User",
    salonName: "Fashion Locks",
    serviceOrPackage: "Hair Style",
    status: "Active",
    bookingDate: "2024-11-30",
    paid: false,
    transactionId: 15,
    amount: 100
  },
  {
    appointmentId: 20,
    userName: "Partner",
    salonName: "Styling Studio",
    serviceOrPackage: "Hair Style",
    status: "New",
    bookingDate: "2024-12-01",
    paid: true,
    transactionId: 1,
    amount: 100
  },
  {
    appointmentId: 21,
    userName: "User",
    salonName: "Luxury Cuts",
    serviceOrPackage: "Hair Style",
    status: "Scheduled",
    bookingDate: "2024-12-02",
    paid: false,
    transactionId: 18,
    amount: 100
  },
  {
    appointmentId: 22,
    userName: "Partner",
    salonName: "Pure Beauty",
    serviceOrPackage: "Hair Style",
    status: "Active",
    bookingDate: "2024-12-03",
    paid: true,
    transactionId: 20,
    amount: 100
  },
  {
    appointmentId: 23,
    userName: "User",
    salonName: "Divine Styles",
    serviceOrPackage: "Hair Style",
    status: "Cancelled",
    bookingDate: "2024-12-04",
    paid: false,
    transactionId: 8,
    amount: 100
  },
  {
    appointmentId: 24,
    userName: "Partner",
    salonName: "Euphoria Salon",
    serviceOrPackage: "Hair Style",
    status: "Scheduled",
    bookingDate: "2024-12-05",
    paid: true,
    transactionId: 27,
    amount: 100
  },
  {
    appointmentId: 25,
    userName: "User",
    salonName: "Charm Salon",
    serviceOrPackage: "Hair Style",
    status: "Active",
    bookingDate: "2024-12-06",
    paid: false,
    transactionId: 13,
    amount: 100
  },
  {
    appointmentId: 26,
    userName: "Partner",
    salonName: "Glow and Go",
    serviceOrPackage: "Hair Style",
    status: "New",
    bookingDate: "2024-12-07",
    paid: true,
    transactionId: 28,
    amount: 100
  },
  {
    appointmentId: 27,
    userName: "User",
    salonName: "Flair Salon",
    serviceOrPackage: "Hair Style",
    status: "Cancelled",
    bookingDate: "2024-12-08",
    paid: false,
    transactionId: 24,
    amount: 100
  },
  {
    appointmentId: 28,
    userName: "Partner",
    salonName: "Posh and Polish",
    serviceOrPackage: "Hair Style",
    status: "Scheduled",
    bookingDate: "2024-12-09",
    paid: true,
    transactionId: 23,
    amount: 100
  },
  {
    appointmentId: 29,
    userName: "User",
    salonName: "Trendy Cuts",
    serviceOrPackage: "Hair Style",
    status: "Active",
    bookingDate: "2024-12-10",
    paid: false,
    transactionId: 26,
    amount: 100
  },
  {
    appointmentId: 30,
    userName: "Partner",
    salonName: "O'Barba",
    serviceOrPackage: "Hair Style",
    status: "Scheduled",
    bookingDate: "2024-12-10",
    paid: false,
    transactionId: 26,
    amount: 100
  }
];

module.exports = appointmentData;