let partnerData = [
  {
    partnerId: 1,
    email: "tom01@gmail.com",
    name: "Tom Anderson",
    phoneNumber: "Tom Anderson",
    status: "Active",
    dateJoined: "28/10/2024",
    country: "USA",
    address: "123 Main St, Springfield, IL",
    businessName: "Tom's Hair Haven",
    duration: "9:00AM - 7:00PM",
    break: "1:00PM - 2:00PM",
    verified: true,
    document: "Aadhaar"
  },
  {
    partnerId: 2,
    email: "jay02@gmail.com",
    name: "Jayden Walker",
    phoneNumber: "Jayden Walker",
    status: "Active",
    dateJoined: "28/10/2024",
    country: "Canada",
    address: "456 Oak St, Toronto, ON",
    businessName: "Jayden's Style Station",
    duration: "10:00AM - 6:00PM",
    break: "2:00PM - 3:00PM",
    verified: false,
    document: "none"
  },
  {
    partnerId: 3,
    email: "kim69@gmail.com",
    name: "Inez Kim",
    phoneNumber: "Inez Kim",
    status: "Active",
    dateJoined: "28/10/2024",
    country: "UK",
    address: "789 Elm St, London, England",
    businessName: "Kim's Chic Cuts",
    duration: "8:00AM - 5:00PM",
    break: "12:00PM - 1:00PM",
    verified: true,
    document: "Passport"
  },
  {
    partnerId: 4,
    email: "Franz10@gmail.com",
    name: "Francisco Henry",
    phoneNumber: "Francisco Henry",
    status: "Inactive",
    dateJoined: "28/10/2024",
    country: "Germany",
    address: "1010 Schloss Str., Berlin",
    businessName: "Francisco's Hair Lab",
    duration: "9:00AM - 6:00PM",
    break: "12:30PM - 1:30PM",
    verified: false,
    document: "none"
  },
  {
    partnerId: 5,
    email: "vilo3@gmail.com",
    name: "Violet Phillips",
    phoneNumber: "Violet Phillips",
    status: "Inactive",
    dateJoined: "28/10/2024",
    country: "Australia",
    address: "23 Beach Rd, Sydney, NSW",
    businessName: "Violet's Wave Cuts",
    duration: "8:30AM - 7:00PM",
    break: "12:00PM - 1:00PM",
    verified: true,
    document: "Driver's License"
  },
  {
    partnerId: 6,
    email: "becker7@gmail.com",
    name: "Rosetta Becker",
    phoneNumber: "Rosetta Becker",
    status: "Inactive",
    dateJoined: "28/10/2024",
    country: "USA",
    address: "35 Ocean Blvd, Miami, FL",
    businessName: "Rosetta's Style Studio",
    duration: "9:00AM - 5:00PM",
    break: "1:00PM - 2:00PM",
    verified: false,
    document: "none"
  },
  {
    partnerId: 7,
    email: "dean56@gmail.com",
    name: "Dean Love",
    phoneNumber: "Dean Love",
    status: "Active",
    dateJoined: "28/10/2024",
    country: "Canada",
    address: "102 Maple Ave, Montreal, QC",
    businessName: "Dean's Groom Room",
    duration: "8:00AM - 6:00PM",
    break: "12:30PM - 1:30PM",
    verified: true,
    document: "PAN"
  },
  {
    partnerId: 8,
    email: "nettie44@gmail.com",
    name: "Nettie Tyler",
    phoneNumber: "Nettie Tyler",
    status: "Active",
    dateJoined: "28/10/2024",
    country: "UK",
    address: "54 Green Lane, Manchester",
    businessName: "Nettie's Hair Nook",
    duration: "9:30AM - 5:30PM",
    break: "1:00PM - 2:00PM",
    verified: false,
    document: "none"
  },
  {
    partnerId: 9,
    email: "lora99@gmail.com",
    name: "Lora Weaver",
    phoneNumber: "Lora Weaver",
    status: "Inactive",
    dateJoined: "28/10/2024",
    country: "Germany",
    address: "12 River Rd, Hamburg",
    businessName: "Lora's Locks",
    duration: "10:00AM - 6:00PM",
    break: "1:00PM - 2:00PM",
    verified: true,
    document: "National ID"
  },
  {
    partnerId: 10,
    email: "vin100@gmail.com",
    name: "Vincent Cannon",
    phoneNumber: "Vincent Cannon",
    status: "Inactive",
    dateJoined: "28/10/2024",
    country: "Australia",
    address: "22 High St, Melbourne",
    businessName: "Vincent's Vintage Styles",
    duration: "8:00AM - 4:00PM",
    break: "12:30PM - 1:30PM",
    verified: false,
    document: "none"
  },
  {
    partnerId: 11,
    email: "Palm45@gmail.com",
    name: "Nettie Palmer",
    phoneNumber: "Nettie Palmer",
    status: "Suspended",
    dateJoined: "28/10/2024",
    country: "USA",
    address: "123 Sunset Blvd, Los Angeles, CA",
    businessName: "Palmer's Perfect Cuts",
    duration: "9:00AM - 6:00PM",
    break: "2:00PM - 3:00PM",
    verified: true,
    document: "Passport"
  },
  {
    partnerId: 12,
    email: "mig14@gmail.com",
    name: "Miguel Harris",
    phoneNumber: "Miguel Harris",
    status: "Inactive",
    dateJoined: "28/10/2024",
    country: "Canada",
    address: "789 King St, Vancouver, BC",
    businessName: "Miguel's Mane Studio",
    duration: "8:30AM - 5:30PM",
    break: "12:00PM - 1:00PM",
    verified: false,
    document: "None"
  },
  {
    partnerId: 13,
    email: "angel10@gmail.com",
    name: "Angel Conner",
    phoneNumber: "Angel Conner",
    status: "Active",
    dateJoined: "28/10/2024",
    country: "UK",
    address: "85 Victoria Rd, Bristol",
    businessName: "Angel's Art of Hair",
    duration: "9:00AM - 6:00PM",
    break: "1:00PM - 2:00PM",
    verified: true,
    document: "Aadhaar"
  },
  {
    partnerId: 14,
    email: "rosalie3@gmail.com",
    name: "Rosalie Singleton",
    phoneNumber: "Rosalie Singleton",
    status: "Suspended",
    dateJoined: "28/10/2024",
    country: "Germany",
    address: "44 Park Ave, Munich",
    businessName: "Rosalie's Razor Cut",
    duration: "10:00AM - 7:00PM",
    break: "1:30PM - 2:30PM",
    verified: false,
    document: "None"
  },
  {
    partnerId: 15,
    email: "harrypotter@gmail.com",
    name: "Harry Potter",
    phoneNumber: "Harry Potter",
    status: "Active",
    dateJoined: "29/10/2024",
    country: "Australia",
    address: "68 Kings Rd, Sydney",
    businessName: "Potter's Parlor",
    duration: "9:00AM - 5:00PM",
    break: "12:00PM - 1:00PM",
    verified: true,
    document: "Driver's License"
  },
  {
    partnerId: 16,
    email: "hermione99@gmail.com",
    name: "Hermione Granger",
    phoneNumber: "Hermione Granger",
    status: "Active",
    dateJoined: "29/10/2024",
    country: "USA",
    address: "12 Willow St, New York, NY",
    businessName: "Granger's Glamour Hub",
    duration: "8:00AM - 4:00PM",
    break: "11:30AM - 12:30PM",
    verified: true,
    document: "Pan"
  },
  {
    partnerId: 17,
    email: "ronweasley@gmail.com",
    name: "Ron Weasley",
    phoneNumber: "Ron Weasley",
    status: "Inactive",
    dateJoined: "29/10/2024",
    country: "Canada",
    address: "56 Lakeside Dr, Ottawa, ON",
    businessName: "Ron's Barber Shop",
    duration: "10:00AM - 6:00PM",
    break: "1:30PM - 2:30PM",
    verified: false,
    document: "None"
  },
  {
    partnerId: 18,
    email: "luna23@gmail.com",
    name: "Luna Lovegood",
    phoneNumber: "Luna Lovegood",
    status: "Active",
    dateJoined: "29/10/2024",
    country: "UK",
    address: "20 Brook St, Oxford",
    businessName: "Luna's Lush Locks",
    duration: "9:30AM - 6:30PM",
    break: "1:00PM - 2:00PM",
    verified: true,
    document: "Passport"
  },
  {
    partnerId: 19,
    email: "dobby42@gmail.com",
    name: "Dobby Elf",
    phoneNumber: "Dobby Elf",
    status: "Suspended",
    dateJoined: "29/10/2024",
    country: "Germany",
    address: "5 Hill Rd, Cologne",
    businessName: "Dobby's Do's",
    duration: "9:00AM - 5:00PM",
    break: "12:30PM - 1:30PM",
    verified: false,
    document: "None"
  },
  {
    partnerId: 20,
    email: "user20@gmail.com",
    name: "Alice Johnson",
    phoneNumber: "123-456-7890",
    status: "Active",
    dateJoined: "2024-10-15",
    country: "USA",
    address: "101 Maple St, New York, NY",
    businessName: "Alice's Beauty Lounge",
    duration: "9:00AM - 6:00PM",
    break: "12:00PM - 1:00PM",
    verified: true,
    document: "Aadhaar"
  },
  {
    partnerId: 21,
    email: "user21@gmail.com",
    name: "Bob Lee",
    phoneNumber: "987-654-3210",
    status: "Active",
    dateJoined: "2024-10-17",
    country: "Canada",
    address: "202 Oak St, Toronto, ON",
    businessName: "Bob's Hair Studio",
    duration: "8:00AM - 5:00PM",
    break: "1:00PM - 2:00PM",
    verified: true,
    document: "Passport"
  },
  {
    partnerId: 22,
    email: "emma22@gmail.com",
    name: "Emma Williams",
    phoneNumber: "123-987-6543",
    status: "Inactive",
    dateJoined: "2024-10-20",
    country: "Australia",
    address: "75 Ocean Rd, Perth",
    businessName: "Emma's Elegant Cuts",
    duration: "10:00AM - 7:00PM",
    break: "2:00PM - 3:00PM",
    verified: false,
    document: "None"
  },
  {
    partnerId: 23,
    email: "noah23@gmail.com",
    name: "Noah Brown",
    phoneNumber: "321-654-0987",
    status: "Active",
    dateJoined: "2024-10-22",
    country: "UK",
    address: "200 Hill St, London",
    businessName: "Noah's Neighborhood Salon",
    duration: "9:00AM - 5:30PM",
    break: "1:30PM - 2:30PM",
    verified: true,
    document: "Driver's License"
  },
  {
    partnerId: 24,
    email: "olivia24@gmail.com",
    name: "Olivia Davis",
    phoneNumber: "789-123-4560",
    status: "Suspended",
    dateJoined: "2024-10-23",
    country: "Canada",
    address: "400 Bay St, Toronto, ON",
    businessName: "Olivia's Oasis",
    duration: "8:00AM - 4:00PM",
    break: "12:00PM - 1:00PM",
    verified: false,
    document: "None"
  },
  {
    partnerId: 25,
    email: "james25@gmail.com",
    name: "James Wilson",
    phoneNumber: "456-789-1234",
    status: "Active",
    dateJoined: "2024-10-24",
    country: "USA",
    address: "300 Elm St, Chicago, IL",
    businessName: "James' Joint",
    duration: "9:30AM - 6:00PM",
    break: "1:00PM - 2:00PM",
    verified: true,
    document: "Passport"
  },
  {
    partnerId: 26,
    email: "isabella26@gmail.com",
    name: "Isabella Martinez",
    phoneNumber: "654-321-7890",
    status: "Inactive",
    dateJoined: "2024-10-25",
    country: "Australia",
    address: "88 Sunset Blvd, Melbourne",
    businessName: "Isabella's Impressions",
    duration: "9:00AM - 5:00PM",
    break: "12:30PM - 1:30PM",
    verified: false,
    document: "None"
  },
  {
    partnerId: 27,
    email: "william27@gmail.com",
    name: "William Garcia",
    phoneNumber: "567-890-1234",
    status: "Active",
    dateJoined: "2024-10-26",
    country: "UK",
    address: "150 Abbey Rd, Liverpool",
    businessName: "William's Wonders",
    duration: "10:00AM - 7:00PM",
    break: "1:00PM - 2:00PM",
    verified: true,
    document: "Pan"
  },
  {
    partnerId: 28,
    email: "sophia28@gmail.com",
    name: "Sophia Martinez",
    phoneNumber: "432-567-8901",
    status: "Suspended",
    dateJoined: "2024-10-27",
    country: "Germany",
    address: "60 Park Ave, Berlin",
    businessName: "Sophia's Salon",
    duration: "8:30AM - 5:30PM",
    break: "12:00PM - 1:00PM",
    verified: false,
    document: "None"
  },
  {
    partnerId: 29,
    email: "michael29@gmail.com",
    name: "Michael Taylor",
    phoneNumber: "789-456-1230",
    status: "Active",
    dateJoined: "2024-10-28",
    country: "Canada",
    address: "789 Maple Rd, Ottawa, ON",
    businessName: "Michael's Magic Touch",
    duration: "9:00AM - 6:00PM",
    break: "1:30PM - 2:30PM",
    verified: true,
    document: "Driver's License"
  }
];

module.exports = partnerData;